name: ThornyaDiscord
version: ${project.version}
main: thornyadiscord.thornyadiscord.ThornyaDiscord
api-version: 1.16
authors: [ Gusttavo13 ]
description: Plugin linked Discord
website: https://thornya.club

commands:
  verificar:
    description: verificar no discord
